// -----------------------------------------------------
// CORE MAP ENGINE (ALL IN /modules/)
// -----------------------------------------------------
import { MapCore } from "./modules/mapCore.js";
import { LayerManager } from "./modules/layerManager.js";
import { MarkerEngine } from "./modules/markerEngine.js";
import { DrawingEngine } from "./modules/drawingEngine.js";
import { RadiusTool } from "./modules/radiusTool.js";
import { PopupEngine } from "./modules/popupEngine.js";
import { TileCacheEngine } from "./modules/tileCacheEngine.js";
import { StorageEngine } from "./modules/storageEngine.js";
import { PerfMonitor } from "./modules/perfMonitor.js";
import { StreetViewShell } from "./modules/streetViewShell.js";

// -----------------------------------------------------
// OSM PROVIDERS (ALL IN /modules/)
// -----------------------------------------------------
import { OSMAccessibilityProvider } from "./modules/osmAccessibilityProvider.js";
import { OSMAccessibilityScoreProvider } from "./modules/osmAccessibilityScoreProvider.js";
import { OSMAdressProvider } from "./modules/osmAdressProvider.js";
import { OSMAitQualityProvider } from "./modules/osmAitQualityProvider.js";
import { OSMAmenityProvider } from "./modules/osmAmenityProvider.js";
import { OSMBikeabilityProvider } from "./modules/osmBikeabilityProvider.js";
import { OSMBoundaryProvider } from "./modules/osmBoundaryProvider.js";
import { OSMBridgeDetailProvider } from "./modules/osmBridgeDetailProvider.js";
import { OSMBridgeProvidr } from "./modules/osmBridgeProvidr.js";
import { OSMBuildingHeightProvider } from "./modules/osmBuildingHeightProvider.js";
import { OSMCafeProvidr } from "./modules/osmCafeProvidr.js";
import { OSMCemeteryProvider } from "./modules/osmCemeteryProvider.js";
import { OSMChargingDetailProvidr } from "./modules/osmChargingDetailProvidr.js";
import { OSMClusterProvider } from "./modules/osmClusterProvider.js";
import { OSMCrimeProxyProvider } from "./modules/osmCrimeProxyProvider.js";
import { OSMCulturalProvider } from "./modules/osmCulturalProvider.js";
import { OSMCyclingProvider } from "./modules/osmCyclingProvider.js";
import { OSMDeliveryProvider } from "./modules/osmDeliveryProvider.js";
import { OSMDisasterAccessProvider } from "./modules/osmDisasterAccessProvider.js";
import { OSMEVChargingProvider } from "./modules/osmEVChargingProvider.js";
import { OSMEarthquakeProvider } from "./modules/osmEarthquakeProvider.js";
import { OSMElevationProvider } from "./modules/osmElevationProvider.js";
import { OSMEmergencyProvider } from "./modules/osmEmergencyProvider.js";
import { OSMFeatureProvider } from "./modules/osmFeatureProvider.js";
import { OSMFireProvider } from "./modules/osmFireProvider.js";
import { OSMFireRiskProvider } from "./modules/osmFireRiskProvider.js";
import { OSMFireStationDistanceProvider } from "./modules/osmFireStationDistanceProvider.js";
import { OSMFitnessProvider } from "./modules/osmFitnessProvider.js";
import { OSMFloodProovider } from "./modules/osmFloodProovider.js";
import { OSMGreenProvider } from "./modules/osmGreenProvider.js";
import { OSMGroceryProvider } from "./modules/osmGroceryProvider.js";
import { OSMHazardProvider } from "./modules/osmHazardProvider.js";
import { OSMHeatStressProvider } from "./modules/osmHeatStressProvider.js";
import { OSMHeatmapProvider } from "./modules/osmHeatmapProvider.js";
import { OSMHospitalDetailProvider } from "./modules/osmHospitalDetailProvider.js";
import { OSMHospitalDistanceProvider } from "./modules/osmHospitalDistanceProvider.js";
import { OSMHydrantDistanceProvider } from "./modules/osmHydrantDistanceProvider.js";
import { OSMIndustrialProvider } from "./modules/osmIndustrialProvider.js";
import { OSMKidFriendProvider } from "./modules/osmKidFriendProvider.js";
import { OSMLandValueProvider } from "./modules/osmLandValueProvider.js";
import { OSMLanduseProvider } from "./modules/osmLanduseProvider.js";
import { OSMLightingProvider } from "./modules/osmLightingProvider.js";
import { OSMMarinaProvider } from "./modules/osmMarinaProvider.js";
import { OSMNightlifeProvider } from "./modules/osmNightlifeProvider.js";
import { OSMNoiseActivityProvider } from "./modules/osmNoiseActivityProvider.js";
import { OSMNoiseBarrierProvider } from "./modules/osmNoiseBarrierProvider.js";
import { OSMNoiseHeatmapProvider } from "./modules/osmNoiseHeatmapProvider.js";
import { OSMNoiseProvider } from "./modules/osmNoiseProvider.js";
import { OSMNoiseRouteProvider } from "./modules/osmNoiseRouteProvider.js";
import { OSMParkingProvider } from "./modules/osmParkingProvider.js";
import { OSMPetFriendlyProvider } from "./modules/osmPetFriendlyProvider.js";
import { OSMPollutionProvider } from "./modules/osmPollutionProvider.js";
import { OSMPopulationProvider } from "./modules/osmPopulationProvider.js";
import { OSMPublicTransportationProvider } from "./modules/osmPublicTransportationProvider.js";
import { OSMQuietRoutingProvider } from "./modules/osmQuietRoutingProvider.js";
import { OSMRestaurantDetailProvider } from "./modules/osmRestaurantDetailProvider.js";
import { OSMRoadQualityProvider } from "./modules/osmRoadQualityProvider.js";
import { OSMRoadWidthProvider } from "./modules/osmRoadWidthProvider.js";
import { OSMRoutingProvider } from "./modules/osmRoutingProvider.js";
import { OSMSafetyProvider } from "./modules/osmSafetyProvider.js";
import { OSMScenicProvider } from "./modules/osmScenicProvider.js";
import { OSMSchoolDistanceProvider } from "./modules/osmSchoolDistanceProvider.js";
import { OSMSearchProvider } from "./modules/osmSearchProvider.js";
import { OSMSeniorFriendProvider } from "./modules/osmSeniorFriendProvider.js";
import { OSMShadeProvider } from "./modules/osmShadeProvider.js";
import { OSMSidewalkProvider } from "./modules/osmSidewalkProvider.js";
import { OSMSlopeProvider } from "./modules/osmSlopeProvider.js";
import { OSMSnowProvider } from "./modules/osmSnowProvider.js";
import { OSMSolarProvider } from "./modules/osmSolarProvider.js";
import { OSMSpeedProvider } from "./modules/osmSpeedProvider.js";
import { OSMTourismDetailProvider } from "./modules/osmTourismDetailProvider.js";
import { OSMTourismProvider } from "./modules/osmTourismProvider.js";
import { OSMTrafficProvider } from "./modules/osmTrafficProvider.js";
import { OSMTransitDistanceProvider } from "./modules/osmTransitDistanceProvider.js";
import { OSMTransitProvidr } from "./modules/osmTransitProvidr.js";
import { OSMTransitQualityProvidr } from "./modules/osmTransitQualityProvidr.js";
import { OSMTreeCanopyProvider } from "./modules/osmTreeCanopyProvider.js";
import { OSMTurnRestrictionProvider } from "./modules/osmTurnRestrictionProvider.js";
import { OSMUtilityProvider } from "./modules/osmUtilityProvider.js";
import { OSMWalkTimeProvider } from "./modules/osmWalkTimeProvider.js";
import { OSMWalkabilityProvider } from "./modules/osmWalkabilityProvider.js";
import { OSMWasteProvider } from "./modules/osmWasteProvider.js";
import { OSMWaterProvider } from "./modules/osmWaterProvider.js";
import { OSMWeatherProvider } from "./modules/osmWeatherProvider.js";
import { OSMLsochroneProvider } from "./modules/osmlsochroneProvider.js";

// -----------------------------------------------------
// SKATE PROVIDERS (ALL IN /modules/)
// -----------------------------------------------------
import { SkateFlowProvider } from "./modules/skateFlowProvider.js";
import { SkateHazardProvider } from "./modules/skateHazardProvider.js";
import { SkateLightingProvider } from "./modules/skateLightingProvider.js";
import { SkateParkProvider } from "./modules/skateParkProvider.js";
import { SkateRouteSafetyProvider } from "./modules/skateRouteSafetyProvider.js";
import { SkateSlopeProvider } from "./modules/skateSlopeProvider.js";
import { SkateSpotFinderProvider } from "./modules/skateSpotFinderProvider.js";
import { SkateSurfaceQualityProvider } from "./modules/skateSurfaceQualityProvider.js";
import { SkateTrafficProvider } from "./modules/skateTrafficProvider.js";
import { SkateVibeProvider } from "./modules/skateVibeProvider.js";

// -----------------------------------------------------
// TREE PROVIDERS (ALL IN /modules/tree/)
// -----------------------------------------------------
import { TreeAccessProvider } from "./modules/tree/treeAccessProvider.js";
import { TreeDensityProvider } from "./modules/tree/treeDensityProvider.js";
import { TreeDropZoneProvider } from "./modules/tree/treeDropZoneProvider.js";
import { TreeEquipmentAccessProvider } from "./modules/tree/treeEquipmentAccessProvider.js";
import { TreeHazardTreeProvider } from "./modules/tree/treeHazardTreeProvider.js";
import { TreeJobEstimatorProvider } from "./modules/tree/treeJobEstimatorProvider.js";
import { TreePowerlineRiskProvider } from "./modules/tree/treePowerlineRiskProvider.js";
import { TreeSpeciesProvider } from "./modules/tree/treeSpeciesProvider.js";
import { TreeStormDamageProvider } from "./modules/tree/treeStormDamageProvider.js";
import { TreeWorksiteSuitabilityProvider } from "./modules/tree/treeWorksiteSuitabilityProvider.js";
import { TreeRiskAssessmentProvider } from "./modules/tree/treeRiskAssessmentProvider.js";
